# Generated by Django 4.1.7 on 2023-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enrollment_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
