# Generated by Django 4.1.7 on 2023-03-28 18:17

import auth_api.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_alter_customuser_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=auth_api.models.CustomDateField(default=django.utils.timezone.now),
        ),
    ]
