# Generated by Django 4.1.7 on 2023-03-28 18:28

import auth_api.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=auth_api.models.CustomDateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
