# Generated by Django 4.1.7 on 2023-03-28 18:34

import auth_api.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=auth_api.models.CustomDateField(default=django.utils.timezone.localdate),
        ),
    ]
