# Generated by Django 4.1.7 on 2023-03-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enrollment_number',
            field=models.IntegerField(default=1234567890, unique=True),
            preserve_default=False,
        ),
    ]
