# Generated by Django 4.1.7 on 2023-03-29 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_alter_customuser_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
