# Generated by Django 4.1.7 on 2023-05-06 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact_no', models.BigIntegerField(blank=True)),
                ('branch', models.CharField(choices=[('CO', 'Computer Engineering'), ('EE', 'Electrical Engineering'), ('ET', 'Electronics and Telecommunication Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=2)),
                ('faculty_type', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_number', models.IntegerField(max_length=12, primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(blank=True, max_length=50)),
                ('mothers_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1)),
                ('branch', models.CharField(choices=[('CO', 'Computer Engineering'), ('EE', 'Electrical Engineering'), ('ET', 'Electronics and Telecommunication Engineering'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering')], max_length=2)),
                ('scheme', models.CharField(default='I', max_length=1)),
                ('contact_no', models.BigIntegerField(blank=True)),
                ('address', models.TextField(null=True)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
