# Generated by Django 4.1.7 on 2023-05-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
